Initial modifications

diff --git a/prompt_powerlinerds_setup b/prompt_powerlinerds_setup
--- a/prompt_powerlinerds_setup
+++ b/prompt_powerlinerds_setup
@@ -9,6 +9,9 @@
 # Authors:
 #   David Rice <me@davidjrice.co.uk>
 
+#load dependencies, from sorin
+pmodload 'helper'
+
 ZSH_THEME_REP_TIME_SINCE_COMMIT_SHORT="%{$fg[green]%}"
 ZSH_THEME_REP_TIME_SINCE_COMMIT_MEDIUM="%{$fg[yellow]%}"
 ZSH_THEME_REP_TIME_SINCE_COMMIT_LONG="%{$fg[red]%}"
@@ -71,7 +74,29 @@ rvm_info_for_prompt() {
   fi
 }
 
-prompt_powerline_precmd() {
+# Returns the last exit code as a colored number
+lastexit() {
+    local EXIT="$?"
+    if [ $EXIT != 0 ]; then
+        # Stripped version... #echo -e "%{$fg[red]%}Last command exited $EXIT!%{$reset_color%}"      # Add red if exit code non 0
+        echo ""
+        echo "Last command exited $EXIT!" #KLUGE!
+    else
+        true
+        # Ignore if 0 #echo -e "$fg[green]$EXIT $reset_color"
+    fi
+}
+
+get_root_char() {
+  if [[ "$(whoami)" == "root" ]];then
+    export POWERLINERDS_ROOTCHAR="# "
+  else
+    export POWERLINERDS_ROOTCHAR=""
+  fi
+}
+
+prompt_powerlinerds_precmd() {
+  lastexit
   # Check for untracked files or updated submodules since vcs_info doesn't.
   if [[ ! -z $(git ls-files --other --exclude-standard 2> /dev/null) ]]; then
     fmt_branch="%b%u%c${__PROMPT_SKWP_COLORS[4]}●%f"
@@ -86,7 +111,7 @@ prompt_powerline_precmd() {
   # zstyle ':prezto:module:ruby' rvm '%r'
 }
 
-prompt_powerline_setup() {
+prompt_powerlinerds_setup() {
   setopt LOCAL_OPTIONS
   unsetopt XTRACE KSH_ARRAYS
   prompt_opts=(cr percent subst)
@@ -94,7 +119,15 @@ prompt_powerline_setup() {
   autoload -Uz add-zsh-hook
   autoload -Uz vcs_info
 
-  add-zsh-hook precmd prompt_powerline_precmd
+  add-zsh-hook precmd prompt_powerlinerds_precmd
+
+  # from sorin theme
+  # Set editor-info parameters.
+  zstyle ':prezto:module:editor:info:completing' format '%B%F{red}...%f%b'
+  zstyle ':prezto:module:editor:info:keymap:primary' format ' %B%F{red}❯%F{yellow}❯%F{green}❯%f%b'
+  zstyle ':prezto:module:editor:info:keymap:primary:overwrite' format ' %F{red}♺%f'
+  zstyle ':prezto:module:editor:info:keymap:alternate' format ' %B%F{green}❮%F{yellow}❮%F{red}❮%f%b'
+  # end 'from'
 
   # Use extended color pallete if available.
   if [[ $TERM = *256color* || $TERM = *rxvt* ]]; then
@@ -132,6 +165,8 @@ prompt_powerline_setup() {
   # %n - user
   # %m - machine hostname
 
+  get_root_char
+
   # local fmt_branch="(${__PROMPT_SKWP_COLORS[1]}%b%f%u%c)"
   local fmt_branch="${__PROMPT_SKWP_COLORS[2]}%b%f%u%c"
   local fmt_action="${__PROMPT_SKWP_COLORS[5]}%a%f"
@@ -148,38 +183,35 @@ prompt_powerline_setup() {
   # TODO: should assign this to local variable? somehow doesn't work correctly.
   rvm_split=("${(s/@/)$(rvm_info_for_prompt)}")
 
-  # if [ "$POWERLINE_RIGHT_B" = "" ]; then
-    # POWERLINE_RIGHT_B=%D{%H:%M:%S}
-    local powerline_right_b=$rvm_split[1]
+  # if [ "$POWERLINERDS_RIGHT_B" = "" ]; then
+    # POWERLINERDS_RIGHT_B=%D{%H:%M:%S}
+    local powerlinerds_right_b=$rvm_split[1]
   # fi
 
-  # if [ "$POWERLINE_RIGHT_A" = "" ]; then
-    local powerline_right_a=$rvm_split[2]
+  # if [ "$POWERLINERDS_RIGHT_A" = "" ]; then
+    local powerlinerds_right_a=$rvm_split[2]
   # fi
 
-  # Setup powerline style colouring
-  POWERLINE_COLOR_BG_GRAY=%K{240}
-  POWERLINE_COLOR_BG_LIGHT_GRAY=%K{240}
-  POWERLINE_COLOR_BG_WHITE=%K{255}
+  # Setup powerlinerds style colouring
+  POWERLINERDS_COLOR_BG_GRAY=%K{240}
+  POWERLINERDS_COLOR_BG_LIGHT_GRAY=%K{240}
+  POWERLINERDS_COLOR_BG_WHITE=%K{255}
 
-  POWERLINE_COLOR_FG_GRAY=%F{240}
-  POWERLINE_COLOR_FG_LIGHT_GRAY=%F{240}
-  POWERLINE_COLOR_FG_WHITE=%F{255}
+  POWERLINERDS_COLOR_FG_GRAY=%F{240}
+  POWERLINERDS_COLOR_FG_LIGHT_GRAY=%F{240}
+  POWERLINERDS_COLOR_FG_WHITE=%F{255}
 
-  POWERLINE_SEPARATOR=$'\uE0B0'
-  POWERLINE_R_SEPARATOR=$'\uE0B2'
+  POWERLINERDS_SEPARATOR=$'\u25b7'
+  POWERLINERDS_R_SEPARATOR=$'\u25c1'
 
-  POWERLINE_LEFT_A="%K{green}%F{white} %~ %k%f%F{green}%K{blue}"$POWERLINE_SEPARATOR
-  POWERLINE_LEFT_B="%k%f%F{white}%K{blue} "'${vcs_info_msg_0_}'" %k%f%F{blue}%K{black}"$POWERLINE_SEPARATOR
-  POWERLINE_LEFT_C=" %k%f%F{white}%K{black}"'$(git_time_details)'" %k%f%F{black}"$POWERLINE_SEPARATOR"%f "
+  POWERLINERDS_LEFT_A="%K{green}%F{white} %~ %k%f%F{green}%K{blue}"$POWERLINERDS_SEPARATOR
+  POWERLINERDS_LEFT_B="%k%f%F{white}%K{blue} "'${vcs_info_msg_0_}'" %k%f%F{blue}%K{black}"$POWERLINERDS_SEPARATOR
+  POWERLINERDS_LEFT_C=" %k%f%F{white}%K{black}"'$(git_time_details)'" %k%f%F{black}"$POWERLINERDS_SEPARATOR"%f "
 
-  PROMPT=$POWERLINE_LEFT_A$POWERLINE_LEFT_B$POWERLINE_LEFT_C
-  # RPROMPT=$POWERLINE_COLOR_FG_WHITE$POWERLINE_R_SEPARATOR"%f$POWERLINE_COLOR_BG_WHITE $POWERLINE_COLOR_FG_GRAY$powerline_right_b "$POWERLINE_R_SEPARATOR"%f%k$POWERLINE_COLOR_BG_GRAY$POWERLINE_COLOR_FG_WHITE $powerline_right_a %f%k"
-  # RPROMPT=$POWERLINE_COLOR_FG_WHITE$POWERLINE_R_SEPARATOR"%f$POWERLINE_COLOR_BG_WHITE $POWERLINE_COLOR_FG_GRAY"'$powerline_right_b'" "$POWERLINE_R_SEPARATOR"%f%k$POWERLINE_COLOR_BG_GRAY$POWERLINE_COLOR_FG_WHITE "'$powerline_right_a'" %f%k"
-  RPROMPT=$POWERLINE_COLOR_FG_WHITE$POWERLINE_R_SEPARATOR"%f$POWERLINE_COLOR_BG_WHITE $POWERLINE_COLOR_FG_GRAY"'$(rvm_info_for_prompt)'" "
+  PROMPT=$POWERLINERDS_LEFT_A$POWERLINERDS_LEFT_B$POWERLINERDS_LEFT_C
+  # RPROMPT=$POWERLINERDS_COLOR_FG_WHITE$POWERLINERDS_R_SEPARATOR"%f$POWERLINERDS_COLOR_BG_WHITE $POWERLINERDS_COLOR_FG_GRAY$powerlinerds_right_b "$POWERLINERDS_R_SEPARATOR"%f%k$POWERLINERDS_COLOR_BG_GRAY$POWERLINERDS_COLOR_FG_WHITE $powerlinerds_right_a %f%k"
+  # RPROMPT=$POWERLINERDS_COLOR_FG_WHITE$POWERLINERDS_R_SEPARATOR"%f$POWERLINERDS_COLOR_BG_WHITE $POWERLINERDS_COLOR_FG_GRAY"'$powerlinerds_right_b'" "$POWERLINERDS_R_SEPARATOR"%f%k$POWERLINERDS_COLOR_BG_GRAY$POWERLINERDS_COLOR_FG_WHITE "'$powerlinerds_right_a'" %f%k"
+  # RPROMPT=$POWERLINERDS_COLOR_FG_GRAY$POWERLINERDS_R_SEPARATOR"%f$POWERLINERDS_COLOR_BG_GRAY $POWERLINERDS_COLOR_FG_WHITE"'$(rvm_info_for_prompt)'" "
 }
 
-prompt_powerline_setup "$@"
-
-
-
+prompt_powerlinerds_setup "$@"
